import axios from "axios"
import Head from "next/head"
import { useRouter } from "next/router"
import { useState } from "react"
import { useForm } from "react-hook-form"

export default function Home() {
  const { register, handleSubmit } = useForm()
  const router = useRouter()

  const redirect = (username) => {
    router.push(`/feeds?id=${username}`)
  }

  const submit = async (data) => {
    redirect(data.username)
    try {
      const registeredUser = await axios.post("/api/user", { data })
      return registeredUser
    } catch (err) {
      throw new Error(err)
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ textAlign: "center" }}>
        <form
          onSubmit={handleSubmit(submit)}
          style={{
            display: "flex",
            width: "100%",
            justifyContent: "center",
            alignItems: "center",
            flexDirection: "column",
          }}
        >
          <input
            type="text"
            {...register("username")}
            placeholder="Enter ur name"
          />
          <input
            type="email"
            {...register("email")}
            placeholder="Enter ur email"
          />
          <input type="submit" value="Register" onClick={redirect} />
        </form>
      </div>
    </div>
  )
}
